### ISSUE TITLE
Saving 2 save states simultaneously causes the game to freeze

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#10]

**Comment by clementgallet** [comment]
This should be fixed by 144cd68316a5a097e3ae0135fc4c5ef99c247a92
Reason was that when saving a state, the main thread tell the other threads to resume (by unlocking a write lock), but did not wait for all threads to resume before resuming itself.

If you would perform another savestate immediately, the main thread would destroy the previous lock, but some threads may not have the time to check on this lock from the previous savestate.

Now, we enforce that all threads are resumed using a semaphore, which remains valid.
