### ISSUE TITLE
Doom64 EX crashes on load

### ISSUE THREAD

**Issue by chungy** [clementgallet/libTAS#102]
Using Doom64 EX built from https://github.com/svkaiser/Doom64EX/commit/03a5e6a5a3a14d66886f62b72431b37ef7336706 and libTAS 1.3.1, the game nearly immediately crashes after sound initialization:
```S_Init: Setting up sound.
[libTAS f:0] Thread 27546 (main) ERROR:     Unsupported stream direction 1
doom64ex: src/hostapi/alsa/pa_linux_alsa.c:847: GropeDevice: Assertion `pcm' failed.
Got unknown message!!!
```

I am running libTAS on Arch Linux with all the current packages up to date.

**Comment by clementgallet** [comment]
I'm not getting any error.

I've compiled the game using the provided `fluidsynth-lite` project, no the system ` fluidsynth` package. Which one did you use ?

**Comment by chungy** [comment]
Good question, I had forgotten about the detail :) examining `ldd`, I definitely used `-DENABLE_SYSTEM_FLUIDSYNTH`.

If I try to build Doom64EX with the fluidsynth submodule instead, the compilation fails... so I really can't use anything but a system one.

**Comment by clementgallet** [comment]
Ok, it looks like it's not a problem with `fluidsynth`, because it is using SDL_Audio to playback sound.

It is probably because you are using PortAudio to playback the sound, which collects information by opening an Alsa connection in capture mode. I'll try to install PortAudio to see if I can fix those issues.

Are you running the game with audio muted or not ? If not, you should be able to run the game with audio muted.

**Comment by chungy** [comment]
It crashes with audio muted, yes.

**Comment by clementgallet** [comment]
If it crashed with audio muted in the tool, it means that PortAudio is used by the game and not by libTAS. This is weird because Doom64EX is using fluidsynth without any audio driver initialized, only to generate the audio into buffers, which are then played by SDL Audio. I guess I'm going to install an Arch then.

Just in case, could you look at file `/etc/conf.d/fluidsynth` if `portaudio` is set for default driver (`AUDIO_DRIVER`), and change it to `alsa` if so ?

**Comment by chungy** [comment]
Seems to have everything commented out by default. Nonetheless, I tried changing it to both `alsa` and `pulseaudio` and both of them give me the exact same error.

**Comment by clementgallet** [comment]
`new_fluid_settings()` was initializing all audio drivers, leading to the crash in portaudio init function. Now, all audio drivers except `alsa` are unregistered before `new_fluid_settings()` call (7f1eb749972d3b62cab332ec8723a40d9a88c26b)
