### ISSUE TITLE
Save prompt doesn't appear if editing has been done through Input Editor

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#112]
Just spent a half hour or so making edits to a movie through the input editor only to lose it when closing because I forgot to enable Recording mode for one frame :(

**Comment by vadosnaprimer** [comment]
This sounds like backup functionality for input is missing in savestates. In usual rerecording emulators savestates are still relevant between sessions, so they can be used to store your progress infinitely between sessions as well. If you haven't saved your last movie variation, and get a crash or something, you simply load a state from the disk and whatever you saved is there.

So while memory state of the TASed application can't be reused between sessions, input should all still be relevant, because every movie savestate stores input from the very beginning. It might desync probably, but it's still very nice to have it preserved between sessions, even without memory states.

This is related to [mid-session backup functionality](https://github.com/clementgallet/libTAS/issues/90) that I requested recently: even if it's taxing in real-time and not helpful between sessions to keep memory states, it's very helpful to preserve just input.

**Comment by clementgallet** [comment]
I'm sorry, I gonna fix that very soon. It may be too late, but can still access the savestate-anchored movies by going to `~/.libtas/states/`, they are stored in separate files. Those movie files are currently deleted when the game is started again, which is actually not useful :(

I could add a functionality to offer the user to load a savestate-anchored movie file from the previous game iteration when he is loading the corresponding savestate

**Comment by vadosnaprimer** [comment]
Hmm, savestate-anchored movie usually means that there's an arbitrary frame the savestate is made at, and the movie only starts from that frame. You mean a different thing, right? If you mean just regular movies stored/embedded in savestates, I doubt they have a special name, so I just call them movie savestates. Because every savestate created with a movie loaded contains that movie in it, by the principle of rerecording.

**Comment by clementgallet** [comment]
Yeah, sorry, that is exactly what I meant.

**Comment by clementgallet** [comment]
Autosaves and save alert when quitting now work when the movie is modified in the input editor (e50f2d8563024502e62b196f2223e9e8548cc7c7)

**Comment by Noahkiq** [comment]
thank you :)
