### ISSUE TITLE
[Multiplayer Improvement] Lock Controllers

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#118]
Being able to lock controllers (including keyboard/mouse) would be nice for multiplayer TASes where I just need a player or two for one section while the others would be used for entertainment later

**Comment by clementgallet** [comment]
Implemented in 7bf99f1c410ac6e7b9a508a7a0a78d410f332010. Right click on an input column to lock (or unlock) it. Locked inputs are not modified in recording mode, and cannot be toggled or edited in the input editor. However, if you are at the end of the movie, you can recording new inputs even when locked.
Inputs are not locked anymore if the input editor is closed, because I think it can confuse the user.

I'm unsure what to do with copy/paste feature. For now, pasting will overwrite locked inputs.

**Comment by Noahkiq** [comment]
this works, thank you :)
