### ISSUE TITLE
Save states work poorly during loading screens in meatboy

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#12]
Either the tool says loading the state is not supported or the tool freezes

**Comment by Matte27** [comment]
The following seems to cause it fairly consistently
1. Reach a certain point (like getting the last key in chad)
2. Load a savestate before said point
3. Load a different savestate before said point
4. Tool freezes and closing it is required to get it working again

**Comment by clementgallet** [comment]
This might have been fixed by 748d54ef4239f26bf9218d62b18e4138544dcb10

**Comment by Matte27** [comment]
Not yet fixed

**Comment by clementgallet** [comment]
Freezes happen because the game closes a thread and creates another thread immediately. Pthread library recycles the thread, so the new thread has the same pthread id, but is a different process. When trying to suspend this thread for a future state saving/loading, the signal fails to reach the thread, so the thread is still active, and the tool infinitely waits for this thread to unsuspend.

**Comment by clementgallet** [comment]
This should be fixed by 384d881d091a062df087cc9d9e7193023f1c4154. Now both pthread id and process tid must be identical for a matched thread.
