### ISSUE TITLE
Save files created with stdio do not appear to syscalls and vice versa.

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#125]
Log example:

```
[libTAS f:432] Thread 23531 (main) fopen call with filename /home/ben/.config/UNDERTALE/undertale.ini and mode wb
[libTAS f:432] Thread 23531 (main)   savefile detected
[libTAS f:432] Thread 23531 (main) fclose call
[libTAS f:601] Thread 23531 (main) __xstat call with path /home/ben/.config/UNDERTALE/undertale.ini
[libTAS f:601] Thread 23531 (main) fopen call with filename assets/undertale.ini and mode rb
[libTAS f:628] Thread 23531 (main) __xstat call with path /home/ben/.config/UNDERTALE/undertale.ini
[libTAS f:628] Thread 23531 (main) fopen call with filename assets/undertale.ini and mode rb
```

I'll try to write a PR to fix this, but I figured I should post it as an issue first.

**Comment by clementgallet** [comment]
DosBox opens files with `fopen64()`, then makes some checks using `fileno()` and `fstat64()`. So the current system for managing savefiles is flawed anyway, because `open_memstream()` used to provide a FILE* stream in memory does not have a file descriptor (`fileno()` returns -1).

I'm not sure what is the way to go. Could we create a unique file descriptor when a stream is opened ? But then we should hope that the file descriptor will only be used by the functions we hook. (Hooking `read()` and `write()` functions would be a real overhead and probably lead to recursive calls)

**Comment by clementgallet** [comment]
Seems to work fine with 6c41598d736c1b60e6b80bdb74f53e2ec20c16cc
