### ISSUE TITLE
Several Citra games fail to load with "Backup savefiles in memory" enabled

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#128]
![image](https://user-images.githubusercontent.com/13265322/50044313-db1c6b80-004f-11e9-8feb-3e1b7bc6a87b.png)

Known games include New Super Mario Bros. 2 and Puyo Puyo Tetris

**Comment by clementgallet** [comment]
It should be related to #125

**Comment by Noahkiq** [comment]
#126 doesn't fix the issue

**Comment by clementgallet** [comment]
The problem was that the path of the created savefile and the path of the checked file were not identical, one did contain a double slash in it, so libTAS failed to match the two paths. Now, I store a canonical form of paths so that matches work better (63782030126b64d5c95c0f753d36b2b21343cf04). It fixes at least Puyo Puyo Tetris.

**Comment by Noahkiq** [comment]
Can confirm NSMB2 loads aswell
