### ISSUE TITLE
Ppsspp sets to Vulkan automatically

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#136]
Vulkan in turn crashes ppsspp for some reason(without libtas as well).

But I double checked ppsspp and made sure OpenGL was enabled(I wouldn’t be able to if Vulkan was set, as it just crashes). So this is odd. 

With the ppsspp crashes every here and there, I’d figure auto restart would benefit.

Can anyone with Vulkan check this out?

**Comment by Noahkiq** [comment]
This doesn't exactly sound like a libTAS issue if it crashes without libTAS. Also, auto restart is for continuing movies when a game crashes, not for just playing the entire movie again when the game crashes, so auto restart is definitely not going to help you here.

**Comment by InfamousKnight** [comment]
By crashes every here and there, I meant it did that with the release package. Not crash on startup because Vulkan was somehow set. It’s an issue with the interim build. Where OpenGL is changed to Vulkan if running in libtas interim. What’s up with that?

**Comment by clementgallet** [comment]
ppsspp probably uses Vulkan through SDL. This is a specific API, that is not implemented in libTAS. I'm unsure if Vulkan support is a priority for libTAS (and I don't know if my system supports it).

This may fix your issue: ppsspp checks OpenGL version from higher to lower, meaning that OpenGL context creation will fail multiple times until it finds a version supported by your GPU. I initially assumed context creation will succeed, and as a consequence pulled up some NULL variables. This was fixed in 58d4cc37af41c6e8199892c9d09619a86fdfe113
