### ISSUE TITLE
Dosbox test drive iii passion loading save state issue

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#142]
Not sure if anything can be done with this, but loading a save state while on the road gives the following error:

[libTAS f:1110] Thread 4001 (main) ERROR: Loading this state is not supported because the thread list has changed since, sorry

Anyway to get around this?

**Comment by clementgallet** [comment]
It means that the game spawned or destroyed a thread between the moment you made a savestate and the current frame. Loading the savestate is disabled because it cannot recover that thread. So you must replay your movie and make your savestates to avoid getting this message.

Check if you have "Recycle threads" enabled, it will lower the chances of getting this issue. There are some suggestions in #114 to help the user, I should work on that.
