### ISSUE TITLE
Restarting doesn't work with savefiles in memory

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#144]
The savegame data is not retained through the restart.

**Comment by clementgallet** [comment]
Savefiles are written back into their file if the game will restart (8b69a56daf9325ab50b070bd983aaba7c2acb1f0). The only issue is that because it is done late in the game exiting (at SaveFile object destruction), it may not work if the game crashes on exit. But I think it is the way to go, because some games could decide to save when exiting.
