### ISSUE TITLE
Sometimes crashes when loading savestates

### ISSUE THREAD

**Issue by heav-4** [clementgallet/libTAS#158]
Trying to TAS Mari0 but it has a random chance to just close the game when I load a savestate. Makes this almost unusable, please help.

**Comment by Noahkiq** [comment]
Make sure Incremental Savestates are off and you're using Mesa graphics
drivers (program should warn you about the latter if it's relevant)

**Comment by clementgallet** [comment]
If you are using the stable version, then you won't have the warning message that noahkiq is mentioning.  So yeah, check which GPU driver you are using.

**Comment by ShayBox** [comment]
I'm getting that warning message, but how do you actually fix that problem, I have mesa installed, and nvidia's proprietary drivers, but it still shows the message and still crashes when using save states.

**Comment by clementgallet** [comment]
If you have an nvidia card, you have to install the nouveau driver. If you have both nouveau and nvidia proprietary drivers installed, you can select nouveau by running (at least on my Debian) `sudo update-alternative --config glx`.

**Comment by ShayBox** [comment]
That's not really an option on any newer nvidia gpu, I use my gpu for more than light work, it's just not realistic to require the driver that's locked to the lowest power state available (Thanks nvidia)

**Comment by clementgallet** [comment]
The reason why we need mesa is to use its OpenGL software driver for savestates, because we cannot save the state of the GPU. Can't you switch to nouveau for TASing and then switch back to nvidia?

You could get a fallback savestate by recording a movie and saving a state. Then you stop the game, start it again and load the state. You will get a message saying that you can load the movie associated with the state. It will run the movie until the frame where you did the savestate.

**Comment by ShayBox** [comment]
I mean I could switch, but that's a huge hassle to do, having to edit a file to remove the nouveau blacklist the nvidia driver puts in place, reboot, and undo that to disable it

That does work, though I mean a more automated system, like an option to switch from the current way of doing savestates to a fallback way that uses the movies but handles it for me instead of me having to close and start it every time it will do all of that for me, and let you save the movie up to the point with the save state button and close/reopen the game and play the movie with the load state button

**Comment by noellekiq** [comment]
i wound up just using an ubuntu 18.04 vm inside my main distro which works alright

**Comment by heav-4** [comment]
Using nouveau makes my computer run at less than 3fps, making it unusable. I struggled to switch back to proprietary NVIDIA drivers. Virtual machines are not an option for me (virtualbox isn't working for some strange reason). What do you recommend I do?

**Comment by clementgallet** [comment]
I'm sorry, I don't know what you could do. If you have a recent Nvidia GPU, maybe you could try getting the most up-to-date nouveau version to see if it works better with your system. I personally have a GeForce GTX 560 Ti and nouveau works fine.

**Comment by heav-4** [comment]
Nouveau should be up to date. Some old NVIDIA drivers also do this... know any alternatives to LibTAS? It is quite unfortunate this has happened.
