### ISSUE TITLE
[Regression] Undertale desync since 1.3.3

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#190]
My Undertale TAS (https://github.com/BenLubar/tobytas/tree/8c5ea709941d8f7a9bf3c04949fc6e03569f2946) desyncs on the latest master (https://github.com/clementgallet/libTAS/commit/1b3f0af19c30b8cd98e328b5b2df4261235feecd) but does fine on the released 1.3.3 version (https://github.com/clementgallet/libTAS/tree/v1.3.3)

I've noticed the desync in the first "rotation of perspective" room (the rooms with three pillars and three colored switches), but it probably happens before that.

Here's the ltm generated from the repository linked above: [undertale.ltm.zip](https://github.com/clementgallet/libTAS/files/2899266/undertale.ltm.zip) (zipped because GitHub doesn't like ltm files)

**Comment by clementgallet** [comment]
Desync is introduced in commit d5f1ff5e57c3bd6acf85b6eaf1f4535eee0c87d6. It happens when you release `right` key during a lag frame and press it again during the next frame. The game only pulls events on the later frame so it is supposed to receive a KeyRelease event followed by a KeyPress event, but the Xlib queue was wrongly acting as a FIFO so the event order was wrong. Fixed in d7752c587e4d8ce77e8e1e5305b49e51ac96d6d1

As a side note, it shows that the game can accept a KeyRelease and a KeyPress event of the same key at the same frame, so it would mean that it is possible to press a key on every frame.
