### ISSUE TITLE
New SDL implementation fails to hook into Baba Is You

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#199]
v1.3.2 successfully connects to the game while v1.3.3... doesn't, and complains about SDL_DYNAPI_ENTRY

(although v1.3.2 barely counts... input doesn't seem to work, music plays even when the game is paused, the game runs in fullscreen, etc...)

**Comment by clementgallet** [comment]
Yeah, this is the same problem with Iconoclasts. SDL library is bundled inside the game executable (Chowdren), so we can't find the address of the original `SDL_DYNAPI_ENTRY()` function using `dlsym()`, because the program was (obviously) not compiled to export its symbols. There should be a way to get this address.

**Comment by jacobly0** [comment]
It should work fine even if we get `SDL_DYNAPI_ENTRY` from an external library (which is what allows us to hook into non-exported SDL symbols in the first place).  However, the issue here is that Chowdren appears to be using a newer SDL than the latest 2.0.9 release, so compiling and installing the latest libSDL might fix it.  If, the issue is actually that Chowdren is using a heavily modified version of SDL, we might have to resort to hacks.

**Comment by clementgallet** [comment]
https://github.com/matpow2/SDL-chowdren

**Comment by jacobly0** [comment]
Yeah, looks like it was just caused by functions that have been added since the last release.  I successfully compiled that repo and set libTAS's Library path to that directory which caused an infinite loop calling SDL functions, so I fixed that issue and found a way to use the statically linked SDL functions in #200, which means that there shouldn't be a need to compile the latest SDL to run games that use it.

**Comment by clementgallet** [comment]
Iconoclasts is working as well.

**Comment by Noahkiq** [comment]
can confirm it works, thanks :)
