### ISSUE TITLE
Crash when saving a state in PCem

### ISSUE THREAD

**Issue by micro500** [clementgallet/libTAS#217]
PCem crashes when I try to make a savestate. [Here](https://github.com/clementgallet/libTAS/files/3066220/pcem.log) is a detailed log of the crash (happens in frame 20). With normal levels of debug messages in the console I see the message 
```[libTAS f:20] Thread 2398 (main) ERROR: area->prot == next_area.prot failed in getNextArea``` right after saving the state. 

I have applied your patch and I have Recycle Threads unchecked as recommended in issue #208

**Comment by slamotas** [comment]
I was getting the same error in my Windows 95 testing. If you uncheck "Voodoo Graphics" in the configuration, the error goes away and you can savestate properly. I'm not sure what libTAS doesn't like about it.

**Comment by clementgallet** [comment]
On this particular setting, the heap is split into several memory segments, with different protections (either with or without the execution flag), libTAS merges all segments into one area for the savestate code, and was assuming that the protections were all the same. Fixed in 28dcbcb43da4991001e2ad4d561809e2e5daf125
