### ISSUE TITLE
Super Hexagon: libGLEW.so.1.6 cannot be found

### ISSUE THREAD

**Issue by heav-4** [clementgallet/libTAS#235]
![image](https://user-images.githubusercontent.com/46372165/59633674-f2dec480-9144-11e9-82ee-9e83cf393043.png)

**Comment by noellekiq** [comment]
set your executable/library paths
![image](https://user-images.githubusercontent.com/13265322/59634849-b186ee80-911d-11e9-98de-2850da25a609.png)
![image](https://user-images.githubusercontent.com/13265322/59634861-b8156600-911d-11e9-9b4b-324fb256cdd5.png)

**Comment by heav-4** [comment]
Set the library path to the folder the executable and .so files were in, now the window opens and immediately closes, no log. Progress...

**Comment by clementgallet** [comment]
Could you try again with the lastest commit?

**Comment by chungy** [comment]
Mind that I am trying the standalone version, rather than the Steam version, but I think there might have been a different issue, since I could get it to run before. I had to set the working directory one directory up, so it could read the data directory. My successful run looks like this:

![image](https://user-images.githubusercontent.com/1094821/60035964-f56c7d00-9662-11e9-92ef-5b35fcb2badb.png)
