### ISSUE TITLE
Wine now doesn't even connnect

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#244]
On latest commit, wine fails to connect to anything wine related. I tested /usr/bin/dosbox and it opens fine. So it seems like a wine only problem.

The terminal just states Attempt #1-10 and fails. It worked before(as in connected) but still either crashed or softlocked. Which is a disappointment as I haven't tried prevent writing to disk in midnight club yet. And now I can't run it at all. I tried 3 different programs: mc2, cat planet, nintendo nightmare, all of which fail to connect.

Any idea whats going on? Is anyone else having this problem?

**Comment by clementgallet** [comment]
Introduced in commit 30427efb23d62a2edc33a3082862fcd1e7f4b942, which disables thread recycling by default. Crash is possibly because threads are being created on the first wine process (the one we don't care about) and the thread manager is not initialized. For some reason, when thread are recycled, this issue was not causing a crash, so it was left unnoticed.

**Comment by InfamousKnight** [comment]
Thats strange, because having recycle threads enabled or not still connected fine before. And on my end recycle threads still is enabled by default. Disabling it seemed to grant better results on midnight club before.
