### ISSUE TITLE
RAM Search Fills RAM

### ISSUE THREAD

**Issue by qixils** [clementgallet/libTAS#268]
Using RAM Search on large games/programs such as Citra cause libTAS to use as much RAM as possible, often locking up a system without enough RAM. Possible solution could be temporary storage, better optimization, not showing results above a certain threshold (a few million), etc

**Comment by clementgallet** [comment]
Currently, each result of a RAM Search is stored inside a `RamWatch<T>` object with T being the value type. On a 64-bit arch, each object takes 8 (previous value) + 8 (address) + 8 (pointer to vtable because derived from virtual class) + 8 (pointer to object in a vector) = 24 bytes.

We could drop the template T storing the type, considering that all searches are done on a single type (as opposed to RAM Watch objects). This would add more code for type casting. Also, if we drop the template, we don't need to rely on inheritance, and we could just store the whole objects inside a vector instead of storing the pointers (+ no more construction/destruction code). So it would cut in half the size (unless I'm missing something).

**Comment by clementgallet** [comment]
Rewrote ram search code in cd857d917b3378c0dbc3afcb0dfc312b81d60995. It seems to take 60% less memory now (so I should have missed another 8 bytes in the original implementation), as well as a speed boost. It doesn't fix the issue entirely though, we still need a limit.

**Comment by clementgallet** [comment]
Should be better with new ram search (2d6bce88802d19a2c16f209785e9cf135ed3bc46)
