### ISSUE TITLE
VVVVVV closes upon launch

### ISSUE THREAD

**Issue by heav-4** [clementgallet/libTAS#285]
Using libTAS v1.3.4 64 bit.
[EDIT] Virtual steam client simply changes the top error to `User is not logged into Steam. Can't get stats.`
In the console:
![image](https://user-images.githubusercontent.com/46372165/68957406-e036ed00-07c1-11ea-95d3-5dfd699bc064.png)

**Comment by clementgallet** [comment]
You can uncheck Virtual Steam client because this game does not require a connection to Steam.

In `File > Executable options` you have to set `Run path` to the game directory (`[steampath]/steamapps/common/vvvvvv/`) and library path to `[steampath]/steamapps/common/vvvvvv/x86_64` assuming you are running the 64-bit version.
