### ISSUE TITLE
Cuphead TAS Desyncs

### ISSUE THREAD

**Issue by Bluely-NO-STALKING-MYSELF-ALLOWED** [clementgallet/libTAS#297]
It desyncs on middle of stage, is there any fix? https://www.youtube.com/watch?v=4osRn7KMRJM

**Comment by clementgallet** [comment]
Is it an input desync (some inputs where dropped or too early/late), or an RNG desync (enemy was at a different place when recording)?

**Comment by BluelyTASer** [comment]
No, it desyncs randomly on loading screens.

**Comment by thomclx** [comment]
Running wine can be tricky, method calls  and behaviours be inconsistent.
I recommend you to experiment with different settings, playing with fast forward etc.... 
I end up making game specific tweaks for THUGPro (disable sound, and bypass glDrawArrays) to make it sync. Even modified wine at first (wined3d/buffer.c), because it desynced with a particular dx version i installed (installing mdx with winetricks does not requires this mod).
https://youtu.be/NW0o4cIye54

**Comment by clementgallet** [comment]
Yuzu is not deterministic, because Switch not deterministic itself (multithreaded), and yuzu spawns a thread for each thread of the emulated console. Specific games may run deterministically if they use only one thread for their whole logic.

**Comment by clementgallet** [comment]
I suggest you look at this to run a native version: https://github.com/DemoJameson/Cuphead.macOStoLinux
