### ISSUE TITLE
Jazzpunk cursor lock

### ISSUE THREAD

**Issue by uselessbrit** [clementgallet/libTAS#298]
I'm trying to TAS Jazzpunk (duh), but im having an issue where the cursor isn't locking with the game.

when the game is running outside of LibTAS its fine, but when its launched in LibTAS the cursor doesnt lock anymore.

any ideas?

**Comment by clementgallet** [comment]
Yes, it is intended. The cursor is not hidden when you launch the game with libTAS, so that you can see what mouse inputs you are doing. The downside is that you cannot click when the cursor is offscreen, it unfocuses the window.

There's a new setting in the current commit called "Mouse relative mode", where the mouse movement is relative to the center of the game screen. You can test it by installing the automated build.

**Comment by uselessbrit** [comment]
Thank you!

I will look into it, thank you for the quick response
