### ISSUE TITLE
Input Editor window is quite huge

### ISSUE THREAD

**Issue by Masterjun3** [clementgallet/libTAS#316]
![inputeditor](https://user-images.githubusercontent.com/22375320/78058930-557a1780-7389-11ea-97d9-abfb749b592f.png)

In a movie with a lot of different input keys, the horizontal size of the Input Editor window is very big.

The single-character column widths are bigger than needed, and a horizontal scrollbar would help a lot.

**Comment by clementgallet** [comment]
It is supposed to resize the columns based on content. Could you try changing the label of a column (right click on a column header), it will trigger the resizing of all column. If it doesn't do anything, then it is probably because of a default minimum width that is too high, and I should change that.

Ok for the scrollbar.

**Comment by Masterjun3** [comment]
Renaming columns makes large columns smaller as intended, but only as far as the smallest ones in the image. So all columns seem to have that default minimum width.

**Comment by clementgallet** [comment]
Could you try if the value I used in commit c545b4f99a8170c4980180cb76576399c8062004 works for you?

**Comment by Masterjun3** [comment]
Yes! That solved the issue I had.

![inpedsolved](https://user-images.githubusercontent.com/22375320/78175738-a2c6b980-745b-11ea-9fdb-aaa72cafa2c4.png)
