### ISSUE TITLE
Input editor: Home and End don't work

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#335]
Should scroll to the very top and bottom respectively.

**Comment by clementgallet** [comment]
Default behavior for home/end keys is weird (I had to look into the source, it is not explained in the doc afaik): those keys move the cursor to the first/last column, but doesn't change the row. To move to the first/last cell, you have to hit Ctrl+Home/End... but it doesn't update the selected row.

So I intercepted the key event for those key strokes, and implemented the expected behavior (485aa7e2fe5c9b23b4771d155e10a7ee491470ae)

**Comment by YaLTeR** [comment]
Oh, thanks, I actually wanted to use Shift+End to select from the currently selected row to the end to then delete the input and paste new input, but that doesn't seem to work even after this patch.

**Comment by clementgallet** [comment]
Oh ok. Indeed it doesn't work because I only implemented the behavior of Home/End with no modifier. I could implement Shift+Home/End as well.

You could do the same think by using "Truncate" option in right-click menu
