### ISSUE TITLE
The Standalone Adobe Flash Player for Linux has Massive Performance Issues

### ISSUE THREAD

**Issue by ItsMaximum** [clementgallet/libTAS#365]
The [Linux Standalone Flash Player](https://github.com/ItsMaximum/flashstuff/blob/master/flashplayer?raw=true) can run inside of libTAS if the path to a .swf file (the compiled form of a flash game) is provided in the command line options. However, no matter what game is tested, there are massive performance and functionality issues. Here are my findings:

[Red Box](https://github.com/ItsMaximum/flashstuff/blob/master/rb.swf?raw=true) (very rudimentary game):

Running the game with all of the default options simply produces a white screen that doesn't progress. However, by checking the "Busy Loop Detection" option in the runtime settings, the game actually starts up. However, the performance is abysmal; 1 or 2 frames are advanced every 3-5 seconds or so. However, movie recording and playback does appear to be working, though its hard to tell whether it is deterministic or not. Savestates do not appear to be working. However, by checking "Uncontrolled Time" in the debug menu, performance is significantly improved. However, for some reason, the game only accepts what seems like one input per second, which is quite unusual. With this enabled, movie recording still works, but movie playback appears to not be deterministic, giving a different result every time that it is run. By enabling "Native Events" in the debug menu, the game plays well, but movie recording and playback are both broken. Also, the frame counter still ticks up way slower in the libTAS menu than it should.

[Red Ball](https://github.com/ItsMaximum/flashstuff/blob/master/rb1.swf?raw=true) (far more robust game):

Just like Red Box, the game doesn't run with the default settings. By enabling "Busy Loop Detection", the game loads, but no mouse or tab input is accepted on the main menu. With "Uncontrolled Time" enabled, the game still refuses to accept any mouse or tab inputs. However, by enabling "Native Events", the game finally plays like it is supposed to. Strangely enough, libTAS ticks up the frame value much faster while in a level than while in any menus. However, just like Red Box, having both of these debug options enabled completely breaks movie recording and playback.

All of these findings were gathered using the latest version of ZorinOS with the nouveau graphics driver (the nvidia drivers handled flash player very poorly). The extremely closed-source nature of flash player could make solving these issues near-impossible, but I felt like it was worthwhile to share my findings nonetheless. There are hundreds of flash games that have seen speedrunning competition, so managing to get Flash Player working on libTAS would open the door to a huge amount of TASing potential for those games.

**Comment by InfoTeddy** [comment]
No one's working on Gnash anymore, and the official player is completely terrible. I'd rather just wait for [Ruffle](https://github.com/ruffle-rs/ruffle) to work for your game(s).

**Comment by clementgallet** [comment]
Once the new Busy Loop Detection code will be implemented, we'll look at this again.

**Comment by clementgallet** [comment]
Adobe Flash Player uses [VDPAU](https://www.freedesktop.org/wiki/Software/VDPAU/) for rendering, which is supported in commit 0bce855a07881eb01758b682ab50f060c1ca9806. Most timing issues were fixed by commit 696d33119ef5e8b38d246c252ecc81e8c7d75f77 (if main thread is polling and timeout, advance ticks to timeout value).

There are still issues to fix:

- savestates crash
- the game frame does not cover the entire top-level window, there is natively a field on top with the .swf file path. In general, libTAS alters the game window position so that screen coordinates and window coordinates matches, which has the side effect of moving the game frame to the top of the window, leaving a small rectangle that is never refreshed
- libTAS program captures inputs from the top-level window, but the game window is not a top-level window, so hotkeys don't work until the user click on the top-level window (outside the game window)
- moving the mouse freezes the game
- hud only appears when the game is paused, otherwise the screen is refreshed again by another mean (probably by gtk framework?)

**Comment by clementgallet** [comment]
The focus problem is solved (e2766b9), and inputs work now (9a48fc5) (yes, inputs weren't working, and I couldn't test because of the other issues).

**Comment by clementgallet** [comment]
Nevermind, the time handling fails at 60 fps. The main loop polls multiple times with too high timeout, so that libTAS adds a non-draw frame exacty one in every 3 frames.
```
libTAS f:63] Thread 44074 (main) poll call with 2 fds and timeout 6
[libTAS f:63] Thread 44074 (main) poll call with 2 fds and timeout 6
[libTAS f:63] Thread 44074 (main) poll call with 2 fds and timeout 10
[libTAS f:63] Thread 44074 (main) poll call with 2 fds and timeout 10
```

**Comment by clementgallet** [comment]
Actually, when running games with uncontrolled time, I'm getting a steady 30 fps for several games. When reading a bit on the internet, it seems that while browser-embeded flash can run at 60 fps, some projectors are limited at 30 fps. Someone noticed that disabling "Hardware accelerated" in the projector recovered 60 fps. However, as rendered with this option uses a different API, libTAS does not support it (yet).

**Comment by InfoTeddy** [comment]
What API does turning off hardware acceleration use?

**Comment by clementgallet** [comment]
XShm

**Comment by clementgallet** [comment]
XShm rendering is now supported when disabling "hardware accelerated" in the flash player options (aa17c623eaded682efc433f5126a1e861c74b1bb and 05fe26bcb817e53e96319deef3cd6e3caed75cd9) -> frames, video capture and HUD. With that option turned off, savestates actually work.

**Comment by clementgallet** [comment]
Fix the screen freeze on mouse movement. GTK uses a `poll()` on the XServer socket connection to check for incoming events, and then calls the relevant Xlib API functions (`XNextEvent()`, etc.). We disabled the input events for the API, but the events were still generated by the server and sent, so that flashplayer was receiving a notification for events, but no actual events.

I modified the event mask so that windows are not interested anymore in input events. Now, no event is generated in the first place (4cc6df9e4c2b93e0fa97cb9902e1a6fa86d46a9b).

**Comment by clementgallet** [comment]
Actually, flashplayer calls `XShmPutImage()` multiple times per frame to draw various elements on screen, so current implementation is faulty. Accelerated alternative (with vdpau) draws once per frame, but is locked at 30 fps for some reason.
