### ISSUE TITLE
1.4.1 broke support for Sonic Robo Blast 2

### ISSUE THREAD

**Issue by Zeritar** [clementgallet/libTAS#385]
Game starts up but doesn't respond to any inputs whatsoever, regardless of movie recording mode being enabled or not. Stop button does nothing either, can only kill the game through terminal.
Tried browsing the console for a while but can't spot anything that stands out.

[console.txt](https://github.com/clementgallet/libTAS/files/5822094/console.txt)

**Comment by clementgallet** [comment]
From your log, it looks like it is because of the fork included in the game code. I don't remember well when I tested this game, but in my version I commented the definition of `NEWSIGNALHANDLER` in the following line: https://github.com/STJr/SRB2/blob/master/src/sdl/i_system.c#L114 , and the game seems to work fine for me on v1.4.1.

The game forks itself from the start and run all the code in the forked process (because of some reason with catching segfault signals with the other process, or something like that). libTAS expects everything to be in a single process, and discards any fork() or any process creation.

If you don't mind changing the game code (with is not even about the game engine), then just comment the above line.

**Comment by Zeritar** [comment]
Will give it a go and see if it causes any other issues. Thanks!

**Comment by Zeritar** [comment]
Worked for a while, then I reverted the workaround for the SDL_Lock/UnlockAudio issue and it started crashing again. Console output of last frame here
[error.txt](https://github.com/clementgallet/libTAS/files/5822670/error.txt)

**Comment by clementgallet** [comment]
Are you getting the same issue as in #358, always at the same place and consistent?

**Comment by Zeritar** [comment]
Yep. It's in a different place now, but it happens consistently.

**Comment by clementgallet** [comment]
Could you provide a demo file that triggers the crash? The one I have goes until the end.

**Comment by Zeritar** [comment]
Here you go. The config file has my control scheme in it. Must also remove gamedata.dat to reset RNG or it will desync before it gets to the crash point. It crashes on frame 7699.
[Crash.zip](https://github.com/clementgallet/libTAS/files/5875543/Crash.zip)

**Comment by clementgallet** [comment]
In the doc, it is allowed to call `SDL_LockAudioDevice()` multiple times, so I fixed that in 502bf90
