### ISSUE TITLE
[Dosbox crash] load forked save state

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#407]
I stumbled across some forked save state feature and tried to use it under dosbox for testing.

From my understanding it lets you jump straight back to work? It saves the whole game process which is why it takes so long to save, but loading it crashes if you:

Record movie with forked save states checked
Advance like 30 frames
Type in some short word
Make a save state
Type in another word
End recording
Playback movie and try to load the save state from frame 3 or something.
After that, it crashes. Does not say "can't load state from previous execution"

I haven't checked the console log for it yet.

**Comment by InfamousKnight** [comment]
Tried to reproduce, and couldn't...

What is that fork to save states do and what advantage does it have?

**Comment by clementgallet** [comment]
This feature creates a fork of the game. Then, this forked process proceeds to write its savestate, while the original process can resume immediately. This is used to prevent the freezing while the savestate is performed, but does not allow loading after game restart.

This has been fixed. The issue was: if you save a state with this feature and then immediately close the game, the savestates are erased, and then the forked process finishes writing the state. So there is a stalled savestate. On next launch, it was wrongly detected.
