### ISSUE TITLE
Consistent memory addresses for ram watch

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#44]

**Comment by clementgallet** [comment]
Address Space Layout Randomization was disabled for the game process (a086f42157012f6cfd7d25d3cd8257e62696f7cd).

However, addresses lying in the heap are still not consistent. This may be due to malloc implementation introducing non-determinism, or multi-threaded allocation order, or program initialization order. We may need to bundle a malloc implementation to control and trace allocations

**Comment by clementgallet** [comment]
Ram watch supporting pointers (800b211f6b2c83fe6938ac2440196694b8228a45) and pointer scanning (0729ca15e1ae52afdedc09159b4ca358c5039886) were implemented to be able to locate ram watches that are correct upon game restart.
