### ISSUE TITLE
The hud in meatboy gets muddled when starting the game in fast-forward mode with no rendering

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#50]
![s](https://user-images.githubusercontent.com/14953641/43036263-b82e2972-8d06-11e8-9a41-5348fcc49f24.png)

**Comment by clementgallet** [comment]
If think I'm going to drop this. I don't think I can dissociate rendering calls that are used for a single frame and rendering calls that are useful for the whole execution. And having a fast fast-forward is very important as software rendering is very slow.

Also this issue is not specific to a game startup. In Towerfall, if you fast forward during a level startup, all foreground non-animated elements won't appear.

**Comment by Matte27** [comment]
In meatboy it is also occurs if the osd framecount is turned off during the movie

**Comment by clementgallet** [comment]
Both issues are fixed in 921bbd8988eda1ea9ffd2a891e37fd4f6081f5d3. The game was deleting and recreating a GL context at the beginning, so OSD texture/fbo were invalid. Now those objects are recreated when the GL context changes.
