### ISSUE TITLE
Fails to run when there are spaces in the path to the game

### ISSUE THREAD

**Issue by SirFireball3521** [clementgallet/libTAS#531]
Terminal output:
```
> libTAS "/home/sirfireball/.steam/steam/steamapps/common/Geometry Dash/GeometryDash.exe" 
Interim commit d2e42681 built on 2023-02-27
	not a dynamic executable
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
readelf: Error: '/home/sirfireball/.local/share/Steam/steamapps/common/Geometry': No such file
readelf: Error: 'Dash/GeometryDash.exe': No such file
```
I have tried both quoting the string and escaping with a backslash, neither work. I also tried creating a symlink to the executable, but that failed as well.

**Comment by CasualPokePlayer** [comment]
The readelf errors are innocuous, their only purpose right now is for hooking onto mono's internal sleep call (for an .exe, this doesn't apply). The "not a dynamic executable" message would be coming from ldd (which makes sense again since this is an .exe, so ldd won't understand it, in this context this again does not matter). The reason it would be failing to run would be unrelated to having a spaces in the path (more likely just due to Wine support being extremely immature and only really works with very old Wine versions, not any "new" Wine versions).
