### ISSUE TITLE
Compilation dies

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#57]
Debian 9.4.0 i386 VM, updated all the deps I could, sdl2, version 2.0.5.

```
[ 30%] Building CXX object CMakeFiles/TAS.dir/src/libTAS/inputs/inputevents.cpp.o
In file included from /libTAS/src/libTAS/inputs/sdlgamecontroller.h:23:0,
                 from /libTAS/src/libTAS/inputs/inputevents.cpp:31:
/libTAS/src/libTAS/inputs/sdljoystick.h:82:10: error: ‘SDL_JoystickType’ does not name a type
 OVERRIDE SDL_JoystickType SDL_JoystickGetDeviceType(int device_index);
          ^~~~~~~~~~~~~~~~
/libTAS/src/libTAS/inputs/sdljoystick.h:110:10: error: ‘SDL_JoystickType’ does not name a type
 OVERRIDE SDL_JoystickType SDL_JoystickGetType(SDL_Joystick * joystick);
          ^~~~~~~~~~~~~~~~
CMakeFiles/TAS.dir/build.make:1094: recipe for target 'CMakeFiles/TAS.dir/src/libTAS/inputs/inputevents.cpp.o' failed
```

Other observations:
- It won't build without `libxcb-xkb-dev`, which isn't mentioned in the readme.
- It also needs `libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev` that were removed from the readme. Looks like those dependencies are just a leftover from the previous dumping tools?

**Comment by vadosnaprimer** [comment]
Installing a newer version of sdl2 (2.0.8) manually from the file resolved this, and I think people with recent sdl2 will have  no problems, but here it looks like cmake should require more recent sdl2. I'm not sure, maybe 2.0.7 has this too.

**Comment by clementgallet** [comment]
Yeah `SDL_JoystickType` struct was introduced in SDL 2.0.6. I've added a definition in the header, so now systems with SDL 2.0.5 should be able to compile it (feab82b5812a21fbfd29618e8e72acdd13b32967)

I added `libxcb-xkb-dev` in the readme. The other ffmpeg libraries were already removed from the cmake file, and I removed them from debian package dependancies. If it is still asking for them, it is possibly because of the cmake cache configuration. You could try removing the `build` directory and rebuilding again (I didn't find a better way).

**Comment by vadosnaprimer** [comment]
Thanks.

**Comment by vadosnaprimer** [comment]
Ah nope, I still get this error during fresh rebuild (on another system):
```
[ 82%] Building CXX object CMakeFiles/linTAS.dir/src/linTAS/ui/EncodeWindow.cpp.o
/home/feos/Desktop/libTAS/src/linTAS/ui/EncodeWindow.cpp:32:10: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by clementgallet** [comment]
Damned! Sorry, I removed it.
