### ISSUE TITLE
Group items in the menus

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#58]
Dunno how to call the ticket properly, but in cases when you have to change a lot of separate itsems in some menu, you have to navigate through all the menu cascades for each of them. A good example is enabling/disabling things to put into debug log.

In .net it's possible to prevent the menu from shutting down after you pick something. Dunno if it's possible here, but another option might be enable/disable all.

**Comment by clementgallet** [comment]
Apparently this is not an existing feature in Qt menus, but can still be mimicked. What I did was adding an event filtering for some menus in the menubar of the program. It detects mouse release events, and if it happened on a checkable option, then it triggers the action but eats up the event, so that it is not passed to the menubar and menus are not closed (af2a413f0061f511e6feb001267a3519aacb0273)

The option to enable/disable everything was present on the old GUI, indeed. I should bring it back.

**Comment by vadosnaprimer** [comment]
Works!
