### ISSUE TITLE
Weird problems with Mari0

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#59]
I tried some older version of love, like 0.10.x, and the release version of mari0. They would run in libTAS, but the movie I have from another person desynced. I tried switching to the latest versions of everything, and experienced unresolvable problems, appearing on _both_ debian 9 and kubuntu 18.04 (both i386).

I install love:
```
sudo add-apt-repository ppa:bartbes/love-stable
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install love
```
Install libTAS deps:

`sudo apt install libc6 libgcc1 libstdc++6 libqt5core5a libqt5gui5 libqt5widgets5 libx11-6 libxcb1 libxcb-keysyms1 libxcb-xkb1 ffmpeg libswresample2 libasound2 libfontconfig1 libfreetype6 libtar0 zlib1g libx11-dev qtbase5-dev qt5-default libtar-dev zlib1g-dev libsdl2-dev extra-cmake-modules libxcb1-dev libxcb-keysyms1-dev libxcb-xkb-dev libasound2-dev libswresample-dev libfreetype6-dev libfontconfig1-dev cmake git`

Get latest libTAS:
```
git clone https://github.com/clementgallet/libTAS.git
```
Install it as said in the readme:
```
cd libTAS
mkdir build
cd build
cmake ..
make
```
Clone latest mari0:
```
git clone https://github.com/Stabyourself/mari0.git
```
Then I'm able to simply execute `love mari0` and the game runs. But I'm absolutely unable to make it run from libTAS.

Game executable:
```
/usr/bin/love
```
Command-line options:
```
/home/feos/Desktop/libTAS/build/mari0
```
I get this every time:
```
Attempt 1: Couldn't connect to socket.
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Couldn't connect to socket.
Attempt 5: Couldn't connect to socket.
Attempt 6: Couldn't connect to socket.
Attempt 7: Couldn't connect to socket.
Attempt 8: Couldn't connect to socket.
Attempt 9: Couldn't connect to socket.
Attempt 10: Couldn't connect to socket.
Got unknown message!!!
```

Executing this from the terminal does launch the game:
```
/usr/bin/love /home/feos/Desktop/libTAS/build/mari0
```
Tried enabling debug logging, and it refuses to log to either the file or the console.

**Comment by clementgallet** [comment]
Yeah, that's an annoying issue. Basically, the game is calling a hooked function very early in the program execution, so that variables of the libtas library are not initialized yet (not even static variables). Our code replacing the hooked function was using an std::set object, which resulted in a crash because it was not initialized. You didn't have any logging because the libtas library didn't have the chance to make a connection with the linTAS program.

It should work with the last commit (17bf7e220afe7b163ed7eef45f15d39d43668890) which makes the std::set dynamically allocated.

**Comment by vadosnaprimer** [comment]
Thanks again!
