### ISSUE TITLE
Audio problems with ruffle at certain framerates

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#600]
The youtube encode of this movie is a good example
https://tasvideos.org/5900M

If the game is meant to run between 30 and 60 fps (exclusively), it will have audio popping with Ruffle.

Technical insight from CasualPokePlayer:

> Ruffle seems to expect to be able to send at least 1470 samples within a game frame (at 44100 Hz, so one 30 fps frame's worth; this is regardless of the actual framerate of the game). If it cant send that many samples (fps in libtas is set > 30), it simply will not send any audio for that frame, and will try next frame to send audio. Now, at 60 fps, this just means the second frame it's able to send 1470 samples and everything works out OK (since 2 60 FPS frames is the same amount of time as 1 30 FPS frame). At 40 FPS, it will instead send over more than 1470 samples, since more time has elasped... which 2 40 FPS frames is 2204 samples worth. I would suspect however it's turning those 1470 samples into 2204 samples is the issue (improperly buffering i guess?)

Hopefully there's a way for libTAS to capture Ruffle audio in a way that prevents this problem.

**Comment by clementgallet** [comment]
The bug was subtle. libTAS accounted for when a single frame does not have an integer number of samples, such as the movie above that has 1102.5 samples per frame. It does so by keeping the fractional part, and adding one sample when the fractional part goes above 1.

The issue was that the function that computes the conversion and handle fractional part was called twice for a single audio source:

* once for the actual mixing
* once for checking if processing the current frame will result in an underrun, and waits a bit so that the audio thread can catch up with the pace of the main thread

So removing the later call to the function and compute the conversion from ticks to samples directly fixed the issue

**Comment by vadosnaprimer** [comment]
Thanks!
