### ISSUE TITLE
Level loading screens desync the TAS! 

### ISSUE THREAD

**Issue by happymimimix** [clementgallet/libTAS#628]
If a game has an animated level loading screen, it won't be count as a level transition in libTAS because there's graphic updates. 
Depending on the hardware, the loading screen could last different number of frames on different device. Causing the TAS to desync by a random number of frames. 
What should I do to solve this problem?

**Comment by happymimimix** [comment]
> Yeah, this issue does not have a general solution. You could frame advance very slowly at specific frames, so that the game has time to load. You can use markers to help automate this, together with the setting `Autopause on markers` in the input editor options

I wonder if it's possible to restrict how many instructions the CPU is allowed to execute every frame? 
If the CPU is slower than the requested speed, let the graphics wait for the CPU to finish executing. 
Maybe something similar to dosbox's CPU cycles. 
This way, everyone has the exact same level loading time when playing the TAS.

**Comment by CasualPokePlayer** [comment]
> I wonder if it's possible to restrict how many instructions the CPU is allowed to execute every frame?

That is not possible to do at so many fundamental levels. Even if you tried to somehow do that, you would still have desyncs regardless (you're still subject to the unpredictable "outside" here; just displaying something to your screen would count as such). And of course, it doesn't work at all once you look at actually wanting pausing or fast forward.

> Maybe something similar to dosbox's CPU cycles.

That works under an emulator which counts *emulated* CPU cycles. libTAS is not an emulator.

---
The issue is mainly fundamentally having multiple threads doing work: libTAS tries to enforce determinism by effectively lying about the time, only allowing the main thread to advance this fake time (triggered by various actions, mainly presenting a new frame). This doesn't work well when the main thread is just waiting on other threads to do work, then proceeding to output "frames" until said work is done, which would end up being a variable amount of frames. There isn't really a way to solve this within libTAS outside of game specific hacks (or sometimes game engine specific hacks, like with Unity), forcing the main thread to wait for these other threads to finish their work.

**Comment by happymimimix** [comment]
> > I wonder if it's possible to restrict how many instructions the CPU is allowed to execute every frame?
> 
> That is not possible to do at so many fundamental levels. Even if you tried to somehow do that, you would still have desyncs regardless (you're still subject to the unpredictable "outside" here; just displaying something to your screen would count as such). And of course, it doesn't work at all once you look at actually wanting pausing or fast forward.
> 
> > Maybe something similar to dosbox's CPU cycles.
> 
> That works under an emulator which counts _emulated_ CPU cycles. libTAS is not an emulator.
> 
> The issue is mainly fundamentally having multiple threads doing work: libTAS tries to enforce determinism by effectively lying about the time, only allowing the main thread to advance this fake time (triggered by various actions, mainly presenting a new frame). This doesn't work well when the main thread is just waiting on other threads to do work, then proceeding to output "frames" until said work is done, which would end up being a variable amount of frames. There isn't really a way to solve this within libTAS outside of game specific hacks (or sometimes game engine specific hacks, like with Unity), forcing the main thread to wait for these other threads to finish their work.

Thanks very much for your reply.
