### ISSUE TITLE
Stability of dependencies

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#80]
I guess you're developing libTAS on Debian Testing+ rather than Stable? It contains some deps only available from Testing+ mirrors (libqt5core5a for example). While it enables some newer features, and also means newest Ubuntu and co. can use it just fine, stable Debian has to install packages from "no so intended" sources.

Is it just a coincidence, and deps can be rolled back to work on stable stable, or newer ones are actually required? Also I don't know if it's theoretically possible to depend on things not available even for stable Ubuntu, but to protect against this scenario I think it makes sense not to drive too fast in that regard.

**Comment by clementgallet** [comment]
Regarding Qt, I always made sure to use functions from Qt 5.6 and below, so it is supposed to be supported by Debian Stable (which uses Qt 5.7). The thing is: for some reason, when you build a program with a certain version of Qt, that version becomes a dependency. The lowest version available I have is an Ubuntu 18.04 VM which is shipped with Qt 5.9. I used it to build the packages, so that is why they depend on Qt 5.9.

If it is a problem, I'll install a VM with another older system which ships with Qt 5.6, so that the packages will get lower requirements.

**Comment by vadosnaprimer** [comment]
Yeah I think supporting stable Debian release without any workarounds is a good goal and it'd mean a lot.

**Comment by clementgallet** [comment]
The release builds have been replaced with ones built on a Debian Stretch. Required Qt version is now 5.7 instead of 5.9.
