### ISSUE TITLE
Support for restarting the game during a movie

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#87]

**Comment by BenLubar** [comment]
Alternate implementation idea: an option to re-launch the game if it exits during playback of a movie and resume the movie from the point where it exited.

**Comment by Noahkiq** [comment]
That kinda misses the point of being able to manually reset immediately after the game saves.

**Comment by clementgallet** [comment]
To handle the case where the game stops itself, I had in mind an option to start a game while resuming the movie recording/playback, and also add a "exit" input in the movie.

**Comment by BenLubar** [comment]
As for "exit" inputs, libTAS could reuse one of the XFree86 key symbols like "quit". I don't think it does anything when sent to most games, and it's esoteric enough that it probably won't be used in any speedruns, but it could be intercepted by libTAS to quit the game instead of sending a key input to the game.

**Comment by vadosnaprimer** [comment]
Why is splitting video at restart a problem?

**Comment by BenLubar** [comment]
Splitting the video would also work.

**Comment by clementgallet** [comment]
Splitting video would be much easier, and splitting is already done at resolution change anyway.

**Comment by BenLubar** [comment]
For anyone needing to restart Undertale specifically, I've written a proxy program:

https://github.com/BenLubar/tobytas/commit/b22767c00202948593ea6d12911f48c8326a92d8

It seems to be working properly without any actual fiddling around with events or anything like that.

I'm not sure whether it properly handles rendering video, but renaming the output file between startups would be a pretty trivial way to do so (and ffmpeg shouldn't be reopening the file, so it'll just continue to finish up the encode on the new filename).

Save files might be a bit weirder, since I'm not sure if they work cross-process...

Here's an .ltm that should be saving the game, but it appears to... not.

(Wrapped in a zip file so GitHub would accept it)

[undertale-test.zip](https://github.com/clementgallet/libTAS/files/2678796/undertale-test.zip)

**Comment by InfamousKnight** [comment]
And where is that option at? I installed latest interim, and ran the executable in there once compiled, and no difference. I installed the release package first though which shouldn’t make any difference. Running Lubuntu natively on i5 core laptop.

**Comment by Noahkiq** [comment]
![image](https://user-images.githubusercontent.com/13265322/50541701-1b640980-0b79-11e9-98da-6cc3a69d0014.png)

**Comment by clementgallet** [comment]
I added a restart input in 99af9b11db175473855cf1607b679d5fa6802fc1. It works like other inputs, you have to map a key to it to be used, and it also appear in the input editor.

I had to change the movie format, of course, but it can still read the former movie format. Also, former libTAS can read new movie format and will ignore the restart input.
