### ISSUE TITLE
Graphical issues in DOSBox

### ISSUE THREAD

**Issue by slamotas** [clementgallet/libTAS#93]
I'm unsure if these are related to each other, but libTAS has a few problems displaying DOSBox:

- OSD elements don't appear
- Doesn't load the screen when loading a state
- Some screen corruption when loading a state and then frame advancing
- When paused and another window is placed over the DOSBox window, the covered area turns black

**Comment by clementgallet** [comment]
The default output option for dosbox is `surface`, which is unsupported for now by libTAS. You may want to change it (in `~/.dosbox/dosbox-0.74-2.conf` for me) to `opengl`, it will solve some issues.

However, if you pause or save a state during a frame that wasn't triggered by a screen draw (you can view it as "lag frame", it's not, but quite similar), then you will have some issues you listed, because we cannot redraw the screen if it wasn't drawn in the first place. Doing so may crash the game (e.g. if we swap opengl front and back buffers in the middle of an opengl routine).

**Comment by slamotas** [comment]
Thanks, switching to opengl fixes the last two issues. OSD is still messed up but that can be turned off for now.

**Comment by clementgallet** [comment]
SDL1 rendering using surfaces is supported in commit 93bb8a4be3aec36108c6213c3131f626a172a188. OSD works correctly with `surface` rendering option.
